### ISSUE TITLE
Group by volume additionally

### ISSUE THREAD

**Issue by theimo1221** [pmaji/crypto-whale-whatching-app#42]
Had a nice and good discussion with Paul. We found many good and some little points.

Pull #41 did a lot of changes towards original goal of detecting whales and fake Resistances/ Supports.

Currrently we spot fakes by grouping price.
An additional approach would be grouping by volume (e.g. 50 orders of 1.53 ETH from $962.65 to $984.42.

At current state we thing adding a bar at the position of summed up volume with the bot beeing at the start and top beeing at the end of price range could be best.

Needed steps to do this:

- [x] Calculate new dataset 
- [x] Grouping dataset
- [x] adding go.bar or rectangle
- [ ] needs description in legend
I guess go.bar won´t work cause we start at different y-levels

**Comment by pmaji** [comment]
Definitely something worth exploring. Lower on the priority list but still an interesting possibility worth of future explanation.

**Comment by theimo1221** [comment]
If #49 get´s pulled this can be closed

**Comment by pmaji** [comment]
@theimo1221 49 was pulled but I think that even with the new annotations being rotated there are still a lot of instances where they overlap. Why not just make them tooltips like with the bubbles?

**Comment by pmaji** [comment]
All good to go. This addition is massively helpful @theimo1221. I'll do a re-write of the README tonight because this changes a lot.

**Comment by pmaji** [comment]
Integrated new information into README; marking issue as completed (just need to add documentation via extensive comments now).
